### ISSUE TITLE
Handling of undefined license

### ISSUE THREAD

**Issue by ischas** [KlausBenndorf/guide4you-builder#21]
When there is no license given in the package.json the header shouldn't look like this:

`* License: undefined (https://spdx.org/licenses/undefined.html)`

but maybe like this:

`* License: NO LICENSE`

**Comment by penpendede** [comment]
I deem "NO LICENSE" too unobtrusive. We'd better use the clear warning _BEWARE: POSSIBLE UNLICENSED USE, THE RISK IS ALL YOURS_ (or something similarly bold) - if that doesn't motivate fixing the issue, nothing will.

**Comment by penpendede** [comment]
It may seem an exaggeration but actually the issue should not occur in the first place.

**Comment by ischas** [comment]
Even if we'd keep an "undefined" it should not link to spdx.

Since it is no big deal to fix it we should fix it soon. We just need to discuss the how.

**Comment by ischas** [comment]
Fixed with https://github.com/KlausBenndorf/guide4you-builder/pull/33
